### ISSUE TITLE
[BUG]: v2.0.2 hostname customization not getting assigned properly on Model 3 B+

### ISSUE THREAD

**Issue by idcrook** [raspberrypi/rpi-imager#1380]
### What happened?

the hostname gets written to uSD card / `user-data` file for cloud-init, but the hostname of the system does not get assigned to the custom value.
On initial (second) boot on newly flashed uSD care (trixie 64-bit lite), the hostname is `raspberrypi`

Using `raspi-config` to manually set the hostname after this point works. That is, upon reboot, the hostname that it was changed to using `raspi-config` is used.

This feature WAS working in v2.0.0, as I performed this same imaging multiple times yesterday (day before v2.0.2 was released) on Model 4 B Pi-s. The custom hostname took in those initial bootups.

### Version

2.0.2 (Default)

### What host operating system were you using?

macOS

### Host OS Version

macOS Tahoe

### Selected OS

Raspberry Pi OS 64-bit trixie Lite

### Which Raspberry Pi Device are you using?

Raspberry Pi 3B, 3A+, 3B+, and Compute Module 3, 3+

### What kind of storage device are you using?

microSD Card in an internal reader

### OS Customisation

- [x] Yes, I was using OS Customisation when the bug occurred.

### Relevant log output

```shell

```

**Comment by zandr** [comment]
I noticed this as well programming a CM5 with Trixie 64-bit Lite.

**Comment by tdewey-rpi** [comment]
Confirmed.

It appears that there's a bit of a catch-22 with cloud-init's hostname configuration system, whereby if you set "preserve_hostname: true", as Imager now does, users can modify their hostname using `raspi-config` and friends. But it never does the first-time hostname setting - it seems to completely discard any hostname directives.

**Comment by slowrunner** [comment]
same issue burning trixie 64-bit lite for Pi3B - hostname customization ignored, "raspberrypi" is hostname setup.

**Comment by nafanz** [comment]
Trixie 64-bit Lite for Pi4B

I encountered the same problem, maybe this will be useful

```
#cloud-config
manage_resolv_conf: false
hostname: qwerty
manage_etc_hosts: true
preserve_hostname: true
packages:
- avahi-daemon
apt:
  preserve_sources_list: true
  conf: |
    Acquire {
      Check-Date "false";
    };
timezone: Asia/Yekaterinburg
keyboard:
  model: pc105
  layout: "ru"
users:
- name: nafanz
  groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo
  shell: /bin/bash
  lock_passwd: false
  passwd: "$y$jB5..."
  ssh_authorized_keys:
    - ssh-rsa AAAAB3Nz...
  sudo: ALL=(ALL) NOPASSWD:ALL
enable_ssh: true
ssh_pwauth: false
rpi:
  interfaces:
    serial: true
```

**Comment by gasteropod** [comment]
I also found that WiFi was blocked by rfkill and I needed to set the WiFi country. This may be related. I reverted back to 2.0.0 in case anything else was not quite right and didn't see either issue.

**Comment by thsvkd** [comment]
> I noticed this as well programming a CM5 with Trixie 64-bit Lite.

I experienced the same thing with the CM4 module. The OS is also the same, Trixie 64-bit Lite.

**Comment by stylesuxx** [comment]
@tdewey-rpi  how is it a catch-22?
Doesn't the `set_hostname` module only run "once per instance" anyway:

```bash
> python3 -c "import cloudinit.config.cc_set_hostname; print(cloudinit.config.cc_set_hostname.meta)"
{'id': 'cc_set_hostname', 'distros': ['all'], 'frequency': 'once-per-instance', 'activate_by_schema_keys': []}
```

So wouldn't removing the `preserve_hostname: true` solve the issue? It would set hostname on first boot, users could afterwards still change it via `raspi-config` without it being affected by `cloud-init` anymore.

**Edit:** It seems this has already been addressed: https://github.com/raspberrypi/rpi-imager/commit/cb3e514324fe1c93fae1b95e84fdfa16bc88034f

**Comment by tdewey-rpi** [comment]
It's a catch-22 because in the current state of Raspberry Pi OS, you can choose either to have Imager write the hostname, and then have to modify it in cloud-init rather than raspi-config, or you can have Imager fail to write the hostname, but raspi-config works as expected.

Regardless, Imager will now at least appear to write the hostname correctly - but be advised due to an issue with cloud-init in Raspberry Pi OS, your chosen hostname will re-apply every boot. I'd suggest modifying the user-data file in the bootfs partition as a workaround.

2.0.3 is now released all over.

**Comment by bledd** [comment]
To get around this issue for now..

sudo nano /boot/firmware/user-data

Update the 
**hostname:** (notice it needs a space after the : )
line, then **sudo reboot now**

**Comment by stylesuxx** [comment]
@bledd just use the latest version of imager, this issue has already been fixed in v2.0.3

**Comment by persep** [comment]
This error still happens with imager-2.0.9 in Windows 11 with a Raspberry Zero 2 W with Trixie 32bits. It ignores any changes applied with `raspi-config`

**Comment by tdewey-rpi** [comment]
> This error still happens with imager-2.0.9 in Windows 11 with a Raspberry Zero 2 W with Trixie 32bits. It ignores any changes applied with `raspi-config`

This isn't an Imager bug.

You'll replicate this on _any_ system running stock cloud-init, including the as-yet unpatched Trixie OS releases.

**Comment by holta** [comment]
@tdewey-rpi is there a ticket in another repo, addressing Raspberry Pi OS's (raspi-config) inability to change its own hostname ?

**Comment by tdewey-rpi** [comment]
> [@tdewey-rpi](https://github.com/tdewey-rpi) is there a ticket in another repo, addressing Raspberry Pi OS's (raspi-config) inability to change its own hostname ?

I wouldn't describe it as Raspberry Pi OS bug.

It's right here: https://github.com/canonical/cloud-init/blame/9c7d85d82c16c2379b1f004623c9d43507f31d3e/cloudinit/cmd/main.py#L1043

And will likely be resolved in the next update to cloud-init in our repos.

Further, you can _manually_ make it Do The Right Thing (tm) by hacking the cloud-init cache, if you can't wait:

- Edit /var/lib/cloud/instances/${your_instance_id}/user-data.txt
- Remove the line starting 'hostname' from that file

OR

`sudo echo "preserve_hostname: true" > /etc/cloud/cloud.cfg.d/98_preserve_hostname.cfg`

OR

If you're particularly keen to never see a user customisation or cloud-init applied setting in your install:

`sudo cloud-init clean && sudo rm /boot/firmware/user-data`

I would, of course, suggest waiting for an update delivered by `apt`

**Comment by persep** [comment]
> > [@tdewey-rpi](https://github.com/tdewey-rpi) is there a ticket in another repo, addressing Raspberry Pi OS's (raspi-config) inability to change its own hostname ?
> If you're particularly keen to never see a user customisation or cloud-init applied setting in your install:
> 
> `sudo cloud-init clean && sudo rm /boot/firmware/user-data`
> 
> I would, of course, suggest waiting for an update delivered by `apt`

Shouldn't `cloud-init` be overruled by manual settings or by using `raspi-config ` and not applied every time you reboot?

**Comment by tdewey-rpi** [comment]
In v2.0.3 of Imager, I introduced a mitigation to do _exactly_ that.

However, that mitigation requires the cloud-init software to cooperate (specifically, to honour it's instance ID behaviours).

Unfortunately, there's a stray unconditional call to set the hostname - which we're patching on our downstream version before I ready a patch for upstream.

**Comment by andras-szuecs** [comment]
> Further, you can _manually_ make it Do The Right Thing (tm) by hacking the cloud-init cache, if you can't wait:
> 
> * Edit /var/lib/cloud/instances/${your_instance_id}/user-data.txt
> * Remove the line starting 'hostname' from that file

For me it only solved the problem after updating the `/boot/firmware/user-data` file and running `sudo cloud-init clean` (and rebooting).  Editing the specific file in `/var/lib/cloud/instances/rpi-imager-1778346392455/user-data.txt` and rebooting changed nothing.
