### ISSUE TITLE
[BUG]: Percent written above 100

### ISSUE THREAD

**Issue by ImCoKeMaN** [raspberrypi/rpi-imager#1432]
### What happened?

When writing a gz file I consistently see writes above 100% with latest version.  Did not see this previously.  Curious if it may be calculating bytes from gz for total, but using extracted size for bytes written.

<img width="658" height="466" alt="Image" src="https://github.com/user-attachments/assets/05cf9a79-c832-4776-a58c-7d43a8dbbcff" />

### Version

2.0.2 (Default)

### What host operating system were you using?

Windows

### Host OS Version

25H2 (pi imager version 2.0.3 but can't select that in dropdown)

### Selected OS

Custom

### Which Raspberry Pi Device are you using?

Raspberry Pi 3B, 3A+, 3B+, and Compute Module 3, 3+

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

### Relevant log output

```shell

```

**Comment by GuestyMC** [comment]
I second this 

<img width="1019" height="718" alt="Image" src="https://github.com/user-attachments/assets/4964b804-dd0f-4f55-b13b-64a1249212bf" />

**Comment by tdewey-rpi** [comment]
> Curious if it may be calculating bytes from gz for total, but using extracted size for bytes written.

That's what I'd put my money on. It's possible that Imager isn't able to correctly identify the unextracted size ahead of time, and is using the extracted size - and then mixing that with the write-reports to create a >1.0 progress.

Delightful UI bug - but shouldn't impact your written OS.

**Comment by tdewey-rpi** [comment]
Fixed in fd5261c, at least as far as is practical

**Comment by davide1995** [comment]
still happening with v.2.0.6

<img width="704" height="497" alt="Image" src="https://github.com/user-attachments/assets/612b37e8-62bc-4b01-b010-786b2742aba6" />

I'm not using a custom file but I chose the 64-bit version of Trixie.

Probably is impacting the written OS because when it achived 119% it started the "Verify" process and aborted with

<img width="699" height="497" alt="Image" src="https://github.com/user-attachments/assets/412b1244-e56c-4124-a046-cbbd4617b163" />
